### ISSUE TITLE
mv: cannot stat 'packer': No such file or directory 

### ISSUE THREAD

**Issue by urbinek** [robertpeteuil/packer-installer#7]
Current script version is failing
```Bash
# ./packer-install.sh
mv: cannot stat 'packer': No such file or directory
```

Issue is in bad unzip command 

```Bash
# EXTRACT ZIP
unzip -f -qq "$FILENAME" || exit 1
```

Flag -f is not needed, so code as such will solve issue:
```Bash
# EXTRACT ZIP
unzip -qq "$FILENAME" || exit 1
```

**Comment by robertpeteuil** [comment]
Thanks for the fix info.  I've incorporated and published a new release that includes this.
